import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import ProductForm from '@/components/forms/ProductForm';
import { useAdd } from '@/lib/tq/products/mutations';
import { ProductFormData } from '@/ts/interfaces/props.interfaces';

export default function AddProduct() {
  const router = useRouter();
  const addMutation = useAdd();

  const submitHandler = (data: ProductFormData) => {
    addMutation.mutate(data);
    router.push('/admin/products/');
  };
  return (
    <>
      <Head>
        <title>Admin Add Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" variant="h4">
          Add Product
        </Heading>
        <ProductForm submitHandler={submitHandler} />
      </Layout>
    </>
  );
}

export const getStaticProps = async () => {
  return {
    props: {},
  };
};
