import Head from 'next/head';
import Link from 'next/link';

import { dehydrate, QueryClient } from '@tanstack/react-query';
import { fetchProducts } from '@/lib/api-functions/server/products/queries';
import { STORAGE_KEY } from '@/lib/tq/products/settings';
import { useDelete } from '@/lib/tq/product/mutations';

import { Button, EditIcon } from '@/components/mui';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import QueryBoundaries from '@/components/QueryBoundaries';
import ProductList from '@/components/ProductList';

export default function AdminProductList() {
  const removeMutation = useDelete();

  const removeHandler = (id: string) => {
    removeMutation.mutate(id);
  };
  return (
    <>
      <Head>
        <title>Admin Add Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" variant="h4">
          Home page
        </Heading>
        <Button
          component={Link}
          variant="contained"
          href={`/admin/products/add`}
        >
          Add Product
        </Button>
        <QueryBoundaries>
          <ProductList deleteHandler={removeHandler} />
        </QueryBoundaries>
        <Button variant="contained">
          Button <EditIcon />
        </Button>
      </Layout>
    </>
  );
}

export const getStaticProps = async () => {
  const products = await fetchProducts().catch((err) =>
    console.log('Index.tsx error', err),
  );
  const queryClient = new QueryClient();

  await queryClient.setQueryData(
    [STORAGE_KEY],
    JSON.parse(JSON.stringify(products)),
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
