import Head from 'next/head';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Link from 'next/link';

import {
  Button,
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  Card,
  CardMedia,
  CardContent,
  CardActions,
} from '@/components/mui';

import Image from 'next/image';

import { AllPosts } from '@/lib/hygraph/queries';

const { HYGRAPH_ENDPOINT, HYGRAPH_TOKEN } = process.env;

export default function BlogPage({ ssd = [] }) {
  console.log('ssd', ssd);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" variant="h4">
          Blog List
        </Heading>
        <List component={'ol'} sx={{ listStyle: 'none' }}>
          {ssd.map(({ id, title, heroImage: { url }, slug }) => (
            <ListItem key={id}>
              <Card component="article" sx={{ width: '100%' }}>
                <CardMedia sx={{ display: 'grid', placeContent: 'center' }}>
                  <Image alt={title} src={url} width="200" height="200" />
                </CardMedia>
                <CardContent>
                  <Heading component="h2" variant="h3">
                    {title}
                  </Heading>
                </CardContent>
                <CardActions>
                  <Link href={`./blog/${slug}`}>Read more...</Link>
                </CardActions>
              </Card>
            </ListItem>
          ))}
        </List>
      </Layout>
    </>
  );
}

export const getStaticProps = async () => {
  const allPosts = await fetch(HYGRAPH_ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': `application/json; charset="UTF-8`,
      Authorization: `Bearer ${HYGRAPH_TOKEN}`,
    },
    body: JSON.stringify({
      query: AllPosts,
    }),
  })
    .then((res) => res.json())
    .catch((err) => console.log(err));
  console.log(allPosts);
  const posts = allPosts.data.blogPosts;
  console.log('posts', posts);
  return {
    props: {
      ssd: posts,
    },
  };
};
