import Head from 'next/head';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import ContactForm from '@/components/forms/ContactForm';
import { sendMail } from '@/lib/api-functions/client';

export default function Contact() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" variant="h4">
          Contact Us
        </Heading>
        <ContactForm submitHandler={sendMail} />
      </Layout>
    </>
  );
}
