import Head from 'next/head';

import { Button, EditIcon } from '@/components/mui';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Paragraph from '@/components/Paragraph';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" variant="h4">
          Home page
        </Heading>
        <Paragraph>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum
          reprehenderit id aspernatur quas dolorum. Eveniet ducimus quis
          corrupti repellendus hic eum esse facere, aut pariatur praesentium
          harum commodi. Maiores, voluptas!
        </Paragraph>
        <Button variant="contained">
          Button <EditIcon />
        </Button>
      </Layout>
    </>
  );
}
