import Head from 'next/head';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Paragraph from '@/components/Paragraph';
import QueryBoundaries from '@/components/QueryBoundaries';
import UserDisplay from '@/components/UserDisplay';
import { UserType } from '@/ts/interfaces/props.interfaces';
import { withPageAuthRequired, getSession } from '@auth0/nextjs-auth0';

export default function Home({ user, sess }: { user: UserType; sess: any }) {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" variant="h4">
          Profile
        </Heading>
        <QueryBoundaries>
          <UserDisplay user={user} />
        </QueryBoundaries>
        <pre>{JSON.stringify(sess, null, 2)}</pre>
      </Layout>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps(context: any) {
    // Getting user data from Auth0
    const session = await getSession(context.req, context.res);
    const user = session ? session.user : null;
    //returns an object like this one: {name: 'Bob', email: 'bob@email.com', email_verified: true}

    // Querying data from DB
    // const { db } = await connectToDatabase()
    // const data = await db.collection("users").find({email: user.email}).project({ first_name: 1 }).toArray()

    return {
      props: { user: user, sess: JSON.parse(JSON.stringify(session)) },
    };
  },
});
